"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { DemoEvidence, platformColors } from "@/lib/demo-data";

export function EvidenceList({ records }: { records: DemoEvidence[] }) {
  const [platform, setPlatform] = useState("全部平台"); const [batch, setBatch] = useState("全部复查记录");
  const [mentioned, setMentioned] = useState("全部提及情况"); const [ranking, setRanking] = useState("全部排名"); const [advantage, setAdvantage] = useState("全部优势判断");
  const [query, setQuery] = useState("");
  const batches = [...new Set(records.map((item) => item.batchName))];
  const rows = useMemo(() => records.filter((item) => (platform === "全部平台" || item.platform === platform) && (batch === "全部复查记录" || item.batchName === batch) && (mentioned === "全部提及情况" || item.mentionedTarget === (mentioned === "提及客户")) && (ranking === "全部排名" || item.rankedTopThree === (ranking === "排名前三")) && (advantage === "全部优势判断" || item.advantageObvious === (advantage === "优势明显")) && (item.question.includes(query) || item.answer.includes(query))), [records, platform, batch, mentioned, ranking, advantage, query]);
  return <section className="evidence-panel"><div className="section-top"><div><p className="eyebrow">原始记录</p><h2>AI 问答记录</h2><p className="muted">每一条结果均保留平台原始回答，可自行核验。</p></div><span className="result-count">{rows.length} 条记录</span></div><div className="filters"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索问题或回答" /><select aria-label="复查记录" value={batch} onChange={(event) => setBatch(event.target.value)}><option>全部复查记录</option>{batches.map((name) => <option key={name}>{name}</option>)}</select><select aria-label="提及客户" value={mentioned} onChange={(event) => setMentioned(event.target.value)}><option>全部提及情况</option><option>提及客户</option><option>未提及客户</option></select><select aria-label="排名" value={ranking} onChange={(event) => setRanking(event.target.value)}><option>全部排名</option><option>排名前三</option><option>未进前三</option></select><select aria-label="优势" value={advantage} onChange={(event) => setAdvantage(event.target.value)}><option>全部优势判断</option><option>优势明显</option><option>优势不明显</option></select></div><div className="platform-filters">{["全部平台", "豆包", "DeepSeek", "元宝", "Kimi", "千问"].map((name) => <button key={name} onClick={() => setPlatform(name)} className={platform === name ? "active" : ""}>{name}</button>)}</div><div className="evidence-table">{rows.map((item) => <Link href={`/client/evidence/${item.id}`} className="evidence-row" key={item.id}><span className="platform-pill" style={{ color: platformColors[item.platform], background: `${platformColors[item.platform]}17` }}>{item.platform}</span><div className="question"><b>{item.question}</b><span>{item.answer}</span></div><div className="tags"><i className={item.mentionedTarget ? "yes" : "no"}>{item.mentionedTarget ? "提及客户" : "未提及客户"}</i><i className={item.rankedTopThree ? "yes" : "no"}>{item.rankedTopThree ? "排名前三" : "未进前三"}</i></div><span className="arrow">→</span></Link>)}</div></section>;
}
